#!/bin/bash

# Regenerates src/fontIds.h for the fonts this fork actually bundles (the
# EN+AR trim removed the other reading families and Noto Sans reading sizes).
# Run after convert-builtin-fonts.sh:
#   ./build-font-ids.sh > ../../../src/fontIds.h
# then re-append/keep the static_assert block at the bottom of fontIds.h if
# your local copy carries one (see the current file).

set -e

cd "$(dirname "$0")/../builtinFonts"

id_for() {
  ruby -rdigest -e 'puts ARGV.map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)' "$@"
}

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

for size in 12 14 16 18; do
  echo "#define BITTER_${size}_FONT_ID ($(id_for ./bitter_${size}_regular.h ./bitter_${size}_bold.h ./bitter_${size}_bolditalic.h ./bitter_${size}_italic.h))"
done
for size in 12 14 16 18; do
  echo "#define LEXENDDECA_${size}_FONT_ID ($(id_for ./lexenddeca_${size}_regular.h ./lexenddeca_${size}_bold.h))"
done
for size in 10 12; do
  echo "#define UI_${size}_FONT_ID ($(id_for ./inter_${size}_regular.h ./inter_${size}_bold.h))"
done
echo "#define SMALL_FONT_ID ($(id_for ./notosans_8_regular.h))"
for size in 8 10 12; do
  echo "#define NOTOSANSARABIC_${size}_FONT_ID ($(id_for ./notosansarabic_${size}_regular.h))"
done
for size in 12 14 16 18; do
  echo "#define NOTONASKHARABIC_${size}_FONT_ID ($(id_for ./notonaskharabic_${size}_regular.h))"
done
for size in 12 14 16 18; do
  echo "#define UTHMANICHAFS_${size}_FONT_ID ($(id_for ./uthmanichafs_${size}_regular.h))"
done
for size in 8 10 12 14 16 18; do
  echo "#define TAJAWAL_${size}_FONT_ID ($(id_for ./tajawal_${size}_regular.h))"
done
echo "#define QURANCOMMON_18_FONT_ID ($(id_for ./quran_common_18_regular.h))"
echo "#define SURAHBANNER_24_FONT_ID ($(id_for ./surah_banner_24_regular.h))"
