#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define NOTOSERIF_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notoserif_12_regular.h",
  "./notoserif_12_bold.h",
  "./notoserif_12_bolditalic.h",
  "./notoserif_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSERIF_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notoserif_14_regular.h",
  "./notoserif_14_bold.h",
  "./notoserif_14_bolditalic.h",
  "./notoserif_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSERIF_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notoserif_16_regular.h",
  "./notoserif_16_bold.h",
  "./notoserif_16_bolditalic.h",
  "./notoserif_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSERIF_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notoserif_18_regular.h",
  "./notoserif_18_bold.h",
  "./notoserif_18_bolditalic.h",
  "./notoserif_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_12_regular.h",
  "./notosans_12_bold.h",
  "./notosans_12_bolditalic.h",
  "./notosans_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_14_regular.h",
  "./notosans_14_bold.h",
  "./notosans_14_bolditalic.h",
  "./notosans_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_16_regular.h",
  "./notosans_16_bold.h",
  "./notosans_16_bolditalic.h",
  "./notosans_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_18_regular.h",
  "./notosans_18_bold.h",
  "./notosans_18_bolditalic.h",
  "./notosans_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_10_regular.h",
  "./ubuntu_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_12_regular.h",
  "./ubuntu_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANSARABIC_8_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosansarabic_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANSARABIC_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosansarabic_10_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANSARABIC_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosansarabic_12_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

# Arabic reading-size fonts (Settings -> Reader -> Arabic Font / Arabic Font Size).
# NOTOSANSARABIC_12 above is reused for this family's reading-Small tier.
for name_size in \
  "NOTOSANSARABIC 14" "NOTOSANSARABIC 16" "NOTOSANSARABIC 18" \
  "NOTONASKHARABIC 12" "NOTONASKHARABIC 14" "NOTONASKHARABIC 16" "NOTONASKHARABIC 18" \
  "AMIRI 12" "AMIRI 14" "AMIRI 16" "AMIRI 18" \
  "SCHEHERAZADENEW 12" "SCHEHERAZADENEW 14" "SCHEHERAZADENEW 16" "SCHEHERAZADENEW 18" \
  "CAIRO 12" "CAIRO 14" "CAIRO 16" "CAIRO 18"; do
  set -- $name_size
  upper=$1
  size=$2
  lower=$(echo "$upper" | tr '[:upper:]' '[:lower:]')
  echo "#define ${upper}_${size}_FONT_ID ($(
  ruby -rdigest -e "puts [
    \"./${lower}_${size}_regular.h\",
  ].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)"
  ))"
done
