#pragma once

#include <builtinFonts/tasbih_32_bold.h>
#include <builtinFonts/stopwatch_32_bold.h>
#include <builtinFonts/lexenddeca_12_bold.h>
#include <builtinFonts/lexenddeca_12_regular.h>
#include <builtinFonts/lexenddeca_14_bold.h>
#include <builtinFonts/lexenddeca_14_regular.h>
#include <builtinFonts/lexenddeca_16_bold.h>
#include <builtinFonts/lexenddeca_16_regular.h>
#include <builtinFonts/lexenddeca_18_bold.h>
#include <builtinFonts/lexenddeca_18_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosansarabic_8_regular.h>
#include <builtinFonts/notosansarabic_10_regular.h>
#include <builtinFonts/notosansarabic_12_regular.h>
#include <builtinFonts/uthmanichafs_12_regular.h>
#include <builtinFonts/uthmanichafs_14_regular.h>
#include <builtinFonts/uthmanichafs_16_regular.h>
#include <builtinFonts/uthmanichafs_18_regular.h>
#include <builtinFonts/tajawal_8_regular.h>
#include <builtinFonts/tajawal_10_regular.h>
#include <builtinFonts/tajawal_12_regular.h>
#include <builtinFonts/tajawal_14_regular.h>
#include <builtinFonts/tajawal_16_regular.h>
#include <builtinFonts/tajawal_18_regular.h>
#include <builtinFonts/quran_common_18_regular.h>
#include <builtinFonts/surah_banner_24_regular.h>
#include <builtinFonts/inter_10_bold.h>
#include <builtinFonts/inter_10_regular.h>
#include <builtinFonts/inter_12_bold.h>
#include <builtinFonts/inter_12_regular.h>
