#pragma once

#include <builtinFonts/notoserif_12_bold.h>
#include <builtinFonts/notoserif_12_bolditalic.h>
#include <builtinFonts/notoserif_12_italic.h>
#include <builtinFonts/notoserif_12_regular.h>
#include <builtinFonts/notoserif_14_bold.h>
#include <builtinFonts/notoserif_14_bolditalic.h>
#include <builtinFonts/notoserif_14_italic.h>
#include <builtinFonts/notoserif_14_regular.h>
#include <builtinFonts/notoserif_16_bold.h>
#include <builtinFonts/notoserif_16_bolditalic.h>
#include <builtinFonts/notoserif_16_italic.h>
#include <builtinFonts/notoserif_16_regular.h>
#include <builtinFonts/notoserif_18_bold.h>
#include <builtinFonts/notoserif_18_bolditalic.h>
#include <builtinFonts/notoserif_18_italic.h>
#include <builtinFonts/notoserif_18_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosansarabic_8_regular.h>
#include <builtinFonts/notosansarabic_10_regular.h>
#include <builtinFonts/notosansarabic_12_regular.h>
#include <builtinFonts/amiri_12_regular.h>
#include <builtinFonts/amiri_14_regular.h>
#include <builtinFonts/amiri_16_regular.h>
#include <builtinFonts/amiri_18_regular.h>
#include <builtinFonts/notonaskharabic_12_regular.h>
#include <builtinFonts/notonaskharabic_14_regular.h>
#include <builtinFonts/notonaskharabic_16_regular.h>
#include <builtinFonts/notonaskharabic_18_regular.h>
#include <builtinFonts/uthmanichafs_12_regular.h>
#include <builtinFonts/uthmanichafs_14_regular.h>
#include <builtinFonts/uthmanichafs_16_regular.h>
#include <builtinFonts/uthmanichafs_18_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
