// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define TASBIH_32_FONT_ID (-1832077162)
#define STOPWATCH_32_FONT_ID (-969373732)
#define LEXENDDECA_12_FONT_ID (-1776708632)
#define LEXENDDECA_14_FONT_ID (352373379)
#define LEXENDDECA_16_FONT_ID (518536303)
#define LEXENDDECA_18_FONT_ID (-2055840923)
#define UI_10_FONT_ID (-312870651)
#define UI_12_FONT_ID (401367925)
#define SMALL_FONT_ID (1565664782)
#define NOTOSANSARABIC_8_FONT_ID (-1117921262)
#define NOTOSANSARABIC_10_FONT_ID (-782696765)
#define NOTOSANSARABIC_12_FONT_ID (2010243675)
#define UTHMANICHAFS_12_FONT_ID (2104988178)
#define UTHMANICHAFS_14_FONT_ID (1641055886)
#define UTHMANICHAFS_16_FONT_ID (-1160315395)
#define UTHMANICHAFS_18_FONT_ID (-413562682)
#define TAJAWAL_8_FONT_ID (-552090769)
#define TAJAWAL_10_FONT_ID (63686576)
#define TAJAWAL_12_FONT_ID (1572681632)
#define TAJAWAL_14_FONT_ID (-1980536858)
#define TAJAWAL_16_FONT_ID (-275170375)
#define TAJAWAL_18_FONT_ID (2026391322)
#define QURANCOMMON_18_FONT_ID (-2088746209)
#define SURAHBANNER_24_FONT_ID (1208078614)

// Font ID 0 is reserved as the "not found" sentinel.
static_assert(TASBIH_32_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(STOPWATCH_32_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANSARABIC_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANSARABIC_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANSARABIC_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UTHMANICHAFS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UTHMANICHAFS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UTHMANICHAFS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UTHMANICHAFS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TAJAWAL_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TAJAWAL_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TAJAWAL_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TAJAWAL_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TAJAWAL_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TAJAWAL_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(QURANCOMMON_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SURAHBANNER_24_FONT_ID != 0, "Font ID collision with sentinel");
