// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (85340443)
#define NOTOSERIF_14_FONT_ID (-1367885987)
#define NOTOSERIF_16_FONT_ID (1428909134)
#define NOTOSERIF_18_FONT_ID (-501438527)
#define UI_10_FONT_ID (-1368565300)
#define UI_12_FONT_ID (-1676426601)
#define SMALL_FONT_ID (1565664782)
#define NOTOSANSARABIC_8_FONT_ID (-1117921262)
#define NOTOSANSARABIC_10_FONT_ID (-782696765)
#define NOTOSANSARABIC_12_FONT_ID (2010243675)
#define NOTONASKHARABIC_12_FONT_ID (-283428235)
#define NOTONASKHARABIC_14_FONT_ID (1701151060)
#define NOTONASKHARABIC_16_FONT_ID (-1686548986)
#define NOTONASKHARABIC_18_FONT_ID (336760565)
#define UTHMANICHAFS_12_FONT_ID (2104988178)
#define UTHMANICHAFS_14_FONT_ID (1641055886)
#define UTHMANICHAFS_16_FONT_ID (-1160315395)
#define UTHMANICHAFS_18_FONT_ID (-413562682)
#define QURANCOMMON_18_FONT_ID (-2088746209)
#define SURAHBANNER_24_FONT_ID (1208078614)

// Font ID 0 is reserved as the "not found" sentinel.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANSARABIC_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANSARABIC_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANSARABIC_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTONASKHARABIC_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTONASKHARABIC_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTONASKHARABIC_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTONASKHARABIC_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UTHMANICHAFS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UTHMANICHAFS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UTHMANICHAFS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UTHMANICHAFS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(QURANCOMMON_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SURAHBANNER_24_FONT_ID != 0, "Font ID collision with sentinel");
